version: '3.4'
services:
  web:
    image: $REPOSITORY/instant-search_web:$TAG
    ports:
     - "5000:5000"
    volumes:
     - conf:/app/conf/
  elasticsearch:
    image: $REPOSITORY/elasticsearch:6.4.2
  db2:
    image: $REPOSITORY/db2express-c-ade:10.5.0.5-3.10.0
    command: db2start
    environment:
    - LICENSE=accept
    - DB2INST1_PASSWORD=$DB2INST1_PASSWORD

volumes:
  conf:
